export const ERROR_MESSAGES = {
  USER_NOT_FOUND: "User not found",
  USER_ALREADY_EXIST: "User already exist",
  INVALID_TOKEN: "Invalid token",
  ACCESS_DENIED: "Access Denied",
  PHOTO_NOT_FOUND: "Photo not found",
  ID_NOT_FOUND: "Id not found",
  SEND_PHOTO: "Please send the photo with key 'photo'",
  INVALID_PASSWORD: "Invalid password",
  INVALID_EMAIL: "Invalid Email",
  INVALID_OLD_PASSWORD: "Invalid old password",
  PASSWORD_NOT_MATCH: "Password is not match",
  VERIFY_EMAIL: "Verify your email",
  ADDRESS_NOT_EXIST: "Address not exist",
  CATEGORY_NOT_EXIST: "Category not exist",
  PRODUCT_NOT_EXIST: "Product not exist",
  CART_NOT_FOUND: "Cart not found",
};
